/********************************************************************
* src/chicoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/chicoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablechicoDict();
extern void G__cpp_setup_inheritancechicoDict();
extern void G__cpp_setup_typetablechicoDict();
extern void G__cpp_setup_memvarchicoDict();
extern void G__cpp_setup_globalchicoDict();
extern void G__cpp_setup_memfuncchicoDict();
extern void G__cpp_setup_funcchicoDict();
extern void G__set_cpp_environmentchicoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/CHICO.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__chicoDictLN_TClass;
extern G__linked_taginfo G__chicoDictLN_TBuffer;
extern G__linked_taginfo G__chicoDictLN_TMemberInspector;
extern G__linked_taginfo G__chicoDictLN_TObject;
extern G__linked_taginfo G__chicoDictLN_TString;
extern G__linked_taginfo G__chicoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__chicoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__chicoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__chicoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__chicoDictLN_CHICOFull;
extern G__linked_taginfo G__chicoDictLN_CHICORaw;
extern G__linked_taginfo G__chicoDictLN_CHICOParticle;

/* STUB derived class for protected member access */
