/********************************************************************
* src/phosWallDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/phosWallDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablephosWallDict();
extern void G__cpp_setup_inheritancephosWallDict();
extern void G__cpp_setup_typetablephosWallDict();
extern void G__cpp_setup_memvarphosWallDict();
extern void G__cpp_setup_globalphosWallDict();
extern void G__cpp_setup_memfuncphosWallDict();
extern void G__cpp_setup_funcphosWallDict();
extern void G__set_cpp_environmentphosWallDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/PhosWall.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__phosWallDictLN_TClass;
extern G__linked_taginfo G__phosWallDictLN_TBuffer;
extern G__linked_taginfo G__phosWallDictLN_TMemberInspector;
extern G__linked_taginfo G__phosWallDictLN_TObject;
extern G__linked_taginfo G__phosWallDictLN_TString;
extern G__linked_taginfo G__phosWallDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__phosWallDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__phosWallDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__phosWallDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__phosWallDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__phosWallDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__phosWallDictLN_TVector3;
extern G__linked_taginfo G__phosWallDictLN_phosWallFull;
extern G__linked_taginfo G__phosWallDictLN_Coeffs;
extern G__linked_taginfo G__phosWallDictLN_Pars;
extern G__linked_taginfo G__phosWallDictLN_Coordinates;
extern G__linked_taginfo G__phosWallDictLN_Neighbours;
extern G__linked_taginfo G__phosWallDictLN_Coeff;
extern G__linked_taginfo G__phosWallDictLN_Calibrate;
extern G__linked_taginfo G__phosWallDictLN_GainMatch;
extern G__linked_taginfo G__phosWallDictLN_hitEvent;
extern G__linked_taginfo G__phosWallDictLN_phosWallRaw;
extern G__linked_taginfo G__phosWallDictLN_vectorlEhitEventcOallocatorlEhitEventgRsPgR;
extern G__linked_taginfo G__phosWallDictLN_vectorlEhitEventcOallocatorlEhitEventgRsPgRcLcLiterator;
extern G__linked_taginfo G__phosWallDictLN_reverse_iteratorlEvectorlEhitEventcOallocatorlEhitEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__phosWallDictLN_calEvent;
extern G__linked_taginfo G__phosWallDictLN_phosWallCalc;
extern G__linked_taginfo G__phosWallDictLN_vectorlEcalEventcOallocatorlEcalEventgRsPgR;
extern G__linked_taginfo G__phosWallDictLN_vectorlEcalEventcOallocatorlEcalEventgRsPgRcLcLiterator;
extern G__linked_taginfo G__phosWallDictLN_reverse_iteratorlEvectorlEcalEventcOallocatorlEcalEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__phosWallDictLN_auxHit;
extern G__linked_taginfo G__phosWallDictLN_phosWallAux;
extern G__linked_taginfo G__phosWallDictLN_vectorlEauxHitcOallocatorlEauxHitgRsPgR;
extern G__linked_taginfo G__phosWallDictLN_vectorlEauxHitcOallocatorlEauxHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__phosWallDictLN_reverse_iteratorlEvectorlEauxHitcOallocatorlEauxHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__phosWallDictLN_maplEintcOTVector3mUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTVector3mUgRsPgRsPgR;

/* STUB derived class for protected member access */
typedef vector<hitEvent,allocator<hitEvent> > G__vectorlEhitEventcOallocatorlEhitEventgRsPgR;
typedef vector<calEvent,allocator<calEvent> > G__vectorlEcalEventcOallocatorlEcalEventgRsPgR;
typedef vector<auxHit,allocator<auxHit> > G__vectorlEauxHitcOallocatorlEauxHitgRsPgR;
